In [4]:
from pathlib import Path

import polars as pl

DATABASE_DIR = Path("../database") if Path("../database").exists() else Path("../database_sample")
EMENDAS_CSV = DATABASE_DIR / "EmendasParlamentares.csv"
CONVENIOS_CSV = DATABASE_DIR / "EmendasParlamentares_Convenios.csv"
FAVORECIDOS_CSV = DATABASE_DIR / "EmendasParlamentares_PorFavorecido.csv"


with open(EMENDAS_CSV, "r", encoding="latin1") as f:
    conteudo = f.read()

EMENDAS_UTF8 = EMENDAS_CSV.with_name(f"{EMENDAS_CSV.stem}_utf8.csv")

with open(EMENDAS_UTF8, "w", encoding="utf-8", newline="") as f:
    f.write(conteudo)


emendas = pl.scan_csv(EMENDAS_UTF8, separator=";", encoding="utf8")
# convenios = pl.scan_csv(CONVENIOS_CSV, separator=';', encoding='latin1')
# favorecidos = pl.scan_csv(FAVORECIDOS_CSV, separator=';', encoding='latin1')

df_emenda = emendas
# df_convenio = convenios
# df_favorecidos = favorecidos

In [5]:
df_emenda.head()

In [6]:
# df_convenio.info()

In [7]:
# df_favorecidos.info()

In [8]:
import polars as pl

dados = pl.read_csv(r"C:\Users\Gabriel Barbosa\Downloads\script_job_6d1db9d69b9435cf5ce2401e037888fb_1.csv", 
                    separator=",", 
                    encoding="utf8",
                    quote_char='"',
                    infer_schema_length=0)

df = pl.DataFrame(dados)

df.head(3)

shape: (3, 31)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ codigo_da ┆ ano_da_em ┆ tipo_de_e ┆ codigo_do ┆ … ┆ valor_res ┆ valor_res ┆ _ingestio ┆ _source_ │
│ _emenda   ┆ enda      ┆ menda     ┆ _autor_da ┆   ┆ tos_a_pag ┆ tos_a_pag ┆ n_timesta ┆ file     │
│ ---       ┆ ---       ┆ ---       ┆ _emenda   ┆   ┆ ar_cancel ┆ ar_pagos  ┆ mp        ┆ ---      │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ ado…      ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆ ---       ┆ str       ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Sem infor ┆ 2014      ┆ Emenda    ┆ S/I       ┆ … ┆ 100000,00 ┆ 0,00      ┆ 2026-10-1 ┆ EmendasP │
│ mação     ┆           ┆ Individua ┆           ┆   ┆           ┆           ┆ 4 02:20:3 ┆ arlament │
│           ┆           ┆ l - Trans ┆           ┆   ┆           ┆           ┆ 6.720322  ┆ ares.csv │
│           ┆           ┆ ferên…    ┆           ┆   ┆           ┆           ┆ UTC       ┆          │
│ Sem infor ┆ 2014      ┆ Emenda    ┆ S/I       ┆ … ┆ 300000,00 ┆ 0,00      ┆ 2026-10-1 ┆ EmendasP │
│ mação     ┆           ┆ Individua ┆           ┆   ┆           ┆           ┆ 4 02:20:3 ┆ arlament │
│           ┆           ┆ l - Trans ┆           ┆   ┆           ┆           ┆ 6.720322  ┆ ares.csv │
│           ┆           ┆ ferên…    ┆           ┆   ┆           ┆           ┆ UTC       ┆          │
│ Sem infor ┆ 2014      ┆ Emenda    ┆ S/I       ┆ … ┆ 0,00      ┆ 500000,00 ┆ 2026-10-1 ┆ EmendasP │
│ mação     ┆           ┆ Individua ┆           ┆   ┆           ┆           ┆ 4 02:20:3 ┆ arlament │
│           ┆           ┆ l - Trans ┆           ┆   ┆           ┆           ┆ 6.720322  ┆ ares.csv │
│           ┆           ┆ ferên…    ┆           ┆   ┆           ┆           ┆ UTC       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
dim_emenda = (
    df
    .filter(
    pl.col('codigo_da_emenda')!='Sem informação'
    )
    .select([
    # Identificador da emenda
        pl.col("codigo_da_emenda").cast(pl.Int64).alias("codigo_da_emenda"),
        pl.col("tipo_de_emenda").str.strip_chars().alias("tipo_emenda"),
        pl.col("ano_da_emenda").cast(pl.Int64).alias("ano_emenda"),
        pl.col("numero_da_emenda").cast(pl.Int64).alias("numero_emenda"),
        
        # Autor
        pl.col("codigo_do_autor_da_emenda").cast(pl.Int64).alias("codigo_autor"),
        pl.col("nome_do_autor_da_emenda").str.strip_chars().alias("nome_autor"),
        pl.col("possui_apoiador_solicitante").str.strip_chars().alias("possui_apoiador_solicitante"),
        
        # Classificação Orçamentária
        pl.col("codigo_funcao").replace("MU", None).cast(pl.Int64).alias("codigo_funcao"),
        pl.col("nome_funcao").str.strip_chars().alias("nome_funcao"),
        pl.col("codigo_subfuncao").replace("MU", None).cast(pl.Int64).alias("codigo_subfuncao"),
        pl.col("nome_subfuncao").str.strip_chars().alias("nome_subfuncao"),

        pl.col('codigo_programa').replace('MU', None).cast(pl.Int64).alias('codigo_programa'),
        pl.col('nome_programa').str.strip_chars().alias('nome_programa'),
        pl.col('codigo_acao').str.strip_chars().alias('codigo_acao'),
        pl.col('nome_acao').str.strip_chars().alias('nome_acao'),

        pl.col('codigo_plano_orcamentario').str.strip_chars().alias('codigo_plano_orcamentario'),
        pl.col('nome_plano_orcamentario').str.strip_chars().alias('nome_plano_orcamentario'),

        # Localidade principal
        pl.col("uf").str.strip_chars().alias("Estado"),

        pl.when(pl.col("uf") == "ACRE").then(pl.lit("AC"))
            .when(pl.col("uf") == "ALAGOAS").then(pl.lit("AL"))
            .when(pl.col("uf") == "AMAPÁ").then(pl.lit("AP"))
            .when(pl.col("uf") == "AMAZONAS").then(pl.lit("AM"))
            .when(pl.col("uf") == "BAHIA").then(pl.lit("BA"))
            .when(pl.col("uf") == "CEARÁ").then(pl.lit("CE"))
            .when(pl.col("uf") == "DISTRITO FEDERAL").then(pl.lit("DF"))
            .when(pl.col("uf") == "ESPÍRITO SANTO").then(pl.lit("ES"))
            .when(pl.col("uf") == "GOIÁS").then(pl.lit("GO"))
            .when(pl.col("uf") == "MARANHÃO").then(pl.lit("MA"))
            .when(pl.col("uf") == "MATO GROSSO").then(pl.lit("MT"))
            .when(pl.col("uf") == "MATO GROSSO DO SUL").then(pl.lit("MS"))
            .when(pl.col("uf") == "MINAS GERAIS").then(pl.lit("MG"))
            .when(pl.col("uf") == "PARÁ").then(pl.lit("PA"))
            .when(pl.col("uf") == "PARAÍBA").then(pl.lit("PB"))
            .when(pl.col("uf") == "PARANÁ").then(pl.lit("PR"))
            .when(pl.col("uf") == "PERNAMBUCO").then(pl.lit("PE"))
            .when(pl.col("uf") == "PIAUÍ").then(pl.lit("PI"))
            .when(pl.col("uf") == "RIO DE JANEIRO").then(pl.lit("RJ"))
            .when(pl.col("uf") == "RIO GRANDE DO NORTE").then(pl.lit("RN"))
            .when(pl.col("uf") == "RIO GRANDE DO SUL").then(pl.lit("RS"))
            .when(pl.col("uf") == "RONDÔNIA").then(pl.lit("RO"))
            .when(pl.col("uf") == "RORAIMA").then(pl.lit("RR"))
            .when(pl.col("uf") == "SANTA CATARINA").then(pl.lit("SC"))
            .when(pl.col("uf") == "SÃO PAULO").then(pl.lit("SP"))
            .when(pl.col("uf") == "SERGIPE").then(pl.lit("SE"))
            .when(pl.col("uf") == "TOCANTINS").then(pl.lit("TO"))
            .when(pl.col("uf") == "Múltiplo").then(pl.lit("MULT"))
            .when(pl.col("uf") == "Sem informação").then(pl.lit("NACI"))
            .otherwise(pl.col("uf"))
            .alias("uf"),
        
        pl.col("localidade_de_aplicacao_do_recurso").str.strip_chars().alias("localidade_recurso"),
        pl.col("codigo_uf_ibge").cast(pl.Int64).alias("codigo_uf_ibge"),
        pl.col("regiao").str.strip_chars().alias("regiao"),

        pl.col("codigo_municipio_ibge").alias("codigo_muninini_ibge"),
        pl.when(
            pl.col('uf') == "Sem informação")
            .then (pl.lit(-1))
                .when(pl.col('uf') == "Múltiplo")
                .then (pl.lit(-14))
            .otherwise(pl.col('codigo_municipio_ibge').replace("Sem informação", -1).cast(pl.Int64))
        .alias('codigo_municipio_ibge'),


        pl.col("municipio"). alias('munini'),
        pl.when(
            pl.col("municipio").replace("Sem informação", None).is_null()
            & pl.col("localidade_de_aplicacao_do_recurso").str.strip_chars().str.ends_with("Nacional"))
            .then(pl.lit("Nacional"))
            .when(
                pl.col("municipio").replace("Sem informação", None).is_null()
                & pl.col("localidade_de_aplicacao_do_recurso").str.strip_chars().str.ends_with("(UF)"))
                .then(pl.lit("Estadual"))
                    .when(
                        pl.col("municipio") == "Sem informação")
                        .then(pl.col('regiao').str.strip_chars())
            .otherwise(
        pl.col("municipio").str.strip_chars())
        .alias("municipio")
    ])
    .unique(subset=['codigo_da_emenda'])
    ).sort(by='ano_emenda', descending=True)


dim_emenda.write_csv(r"C:\Users\Gabriel Barbosa\Downloads\dim_emenda2.csv", include_header=True, separator=',', )
print(dim_emenda)

shape: (13_459, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ codigo_da ┆ tipo_emen ┆ ano_emend ┆ numero_em ┆ … ┆ codigo_mu ┆ codigo_mu ┆ munini    ┆ municipi │
│ _emenda   ┆ da        ┆ a         ┆ enda      ┆   ┆ ninini_ib ┆ nicipio_i ┆ ---       ┆ o        │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ge        ┆ bge       ┆ str       ┆ ---      │
│ i64       ┆ str       ┆ i64       ┆ i64       ┆   ┆ ---       ┆ ---       ┆           ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ i64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 202542580 ┆ Emenda    ┆ 2025      ┆ 13        ┆ … ┆ Sem infor ┆ -1        ┆ Sem infor ┆ Estadual │
│ 013       ┆ Individua ┆           ┆           ┆   ┆ mação     ┆           ┆ mação     ┆          │
│           ┆ l - Trans ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ferên…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 202528620 ┆ Emenda    ┆ 2025      ┆ 5         ┆ … ┆ Sem infor ┆ -1        ┆ Sem infor ┆ Estadual │
│ 005       ┆ Individua ┆           ┆           ┆   ┆ mação     ┆           ┆ mação     ┆          │
│           ┆ l - Trans ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ferên…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 202542650 ┆ Emenda    ┆ 2025      ┆ 9         ┆ … ┆ Sem infor ┆ -1        ┆ Sem infor ┆ Nacional │
│ 009       ┆ Individua ┆           ┆           ┆   ┆ mação     ┆           ┆ mação     ┆          │
│           ┆ l - Trans ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ferên…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 202542990 ┆ Emenda    ┆ 2025      ┆ 12        ┆ … ┆ Sem infor ┆ -1        ┆ Sem infor ┆ Estadual │
│ 012       ┆ Individua ┆           ┆           ┆   ┆ mação     ┆           ┆ mação     ┆          │
│           ┆ l - Trans ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ferên…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 202543440 ┆ Emenda    ┆ 2025      ┆ 14        ┆ … ┆ Sem infor ┆ -1        ┆ Sem infor ┆ Nacional │
│ 014       ┆ Individua ┆           ┆           ┆   ┆ mação     ┆           ┆ mação     ┆          │
│           ┆ l - Trans ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ferên…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 201526830 ┆ Emenda    ┆ 2015      ┆ 1         ┆ … ┆ Sem infor ┆ -1        ┆ Sem infor ┆ Nacional │
│ 001       ┆ Individua ┆           ┆           ┆   ┆ mação     ┆           ┆ mação     ┆          │
│           ┆ l - Trans ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ferên…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 201524370 ┆ Emenda    ┆ 2015      ┆ 12        ┆ … ┆ 2304301   ┆ 2304301   ┆ FARIAS    ┆ FARIAS   │
│ 012       ┆ Individua ┆           ┆           ┆   ┆           ┆           ┆ BRITO     ┆ BRITO    │
│           ┆ l - Trans ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ferên…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 201526140 ┆ Emenda    ┆ 2015      ┆ 3         ┆ … ┆ 2106755   ┆ 2106755   ┆ MIRANDA   ┆ MIRANDA  │
│ 003       ┆ Individua ┆           ┆           ┆   ┆           ┆           ┆ DO NORTE  ┆ DO NORTE │
│           ┆ l - Trans ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ferên…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 201534330 ┆ Emenda    ┆ 2015      ┆ 6         ┆ … ┆ 2304400   ┆ 2304400   ┆ FORTALEZA ┆ FORTALEZ │
│ 006       ┆ Individua ┆           ┆           ┆   ┆           ┆           ┆           ┆ A        │
│           ┆ l - Trans ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ferên…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 201528280 ┆ Emenda    ┆ 2015      ┆ 11        ┆ … ┆ Sem infor ┆ -1        ┆ Sem infor ┆ Nacional │
│ 011       ┆ Individua ┆           ┆           ┆   ┆ mação     ┆           ┆ mação     ┆          │
│           ┆ l - Trans ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ferên…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
import polars as pl

dados_c = pl.read_csv(r"C:\Users\Gabriel Barbosa\Downloads\job_JRrPmEMITywCw-1PMK3MrFXPK_H9.csv", 
                    separator=",", 
                    encoding="utf8",
                    quote_char='"',
                    infer_schema_length=0)

df_c = pl.DataFrame(dados_c)

df_c.head(3)

shape: (3, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ codigo_da ┆ codigo_fu ┆ nome_func ┆ codigo_su ┆ … ┆ numero_co ┆ valor_con ┆ _ingestio ┆ _source_ │
│ _emenda   ┆ ncao      ┆ ao        ┆ bfuncao   ┆   ┆ nvenio    ┆ venio     ┆ n_timesta ┆ file     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ mp        ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 201511420 ┆ 21        ┆ Organizaç ┆ 631       ┆ … ┆ 823345    ┆ 1189081,2 ┆ 2026-10-1 ┆ EmendasP │
│ 009       ┆           ┆ ão        ┆           ┆   ┆           ┆ 8         ┆ 9 02:38:1 ┆ arlament │
│           ┆           ┆ agrária   ┆           ┆   ┆           ┆           ┆ 1.677617  ┆ ares_Con │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ UTC       ┆ venios…  │
│ 201511460 ┆ 21        ┆ Organizaç ┆ 631       ┆ … ┆ 824124    ┆ 1972687,2 ┆ 2026-10-1 ┆ EmendasP │
│ 001       ┆           ┆ ão        ┆           ┆   ┆           ┆ 8         ┆ 9 02:38:1 ┆ arlament │
│           ┆           ┆ agrária   ┆           ┆   ┆           ┆           ┆ 1.677617  ┆ ares_Con │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ UTC       ┆ venios…  │
│ 201511460 ┆ 21        ┆ Organizaç ┆ 631       ┆ … ┆ 823988    ┆ 1000000,0 ┆ 2026-10-1 ┆ EmendasP │
│ 001       ┆           ┆ ão        ┆           ┆   ┆           ┆ 0         ┆ 9 02:38:1 ┆ arlament │
│           ┆           ┆ agrária   ┆           ┆   ┆           ┆           ┆ 1.677617  ┆ ares_Con │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ UTC       ┆ venios…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:

fato_convenios = (
    df_c
    .filter(
    pl.col("codigo_da_emenda").is_not_null()
    & (pl.col('codigo_da_emenda')!='Sem informação')
    )
    .select([
        pl.col("codigo_da_emenda").cast(pl.Int64).alias("codigo_da_emenda"),
        pl.col('codigo_funcao').cast(pl.Int64).alias('codigo_funcao'),
        pl.col('codigo_subfuncao').cast(pl.Int64).alias('codigo_subfuncao'),
        pl.col("numero_convenio").alias("numero_convenio"),
        pl.col('data_publicacao_convenio').str.strptime(pl.Date, format="%d/%m/%Y").alias('data_publicacao_convenio'),

        pl.col('nome_funcao').alias('nome_funcao'),
        pl.col("nome_subfuncao").alias("nome_subfuncao"),

        pl.col("localidade_do_gasto").alias("localidade_do_gasto"),

        pl.when(
            pl.col("localidade_do_gasto").str.strip_chars().str.ends_with("Nacional"))
            .then(pl.lit("Nacional"))
                .when(
                pl.col("localidade_do_gasto").str.strip_chars().str.ends_with("(UF)"))
                .then(pl.lit("Estadual"))
                    .when(
                        pl.col("localidade_do_gasto").str.strip_chars().str.contains(r"(Norte|Sul|Centro-Oeste|Nordeste|Sudeste)$"))
                        .then(pl.lit('Regional'))
                .otherwise(pl.col("localidade_do_gasto").str.strip_chars().str.slice(-2))
                .alias("localidade_classificada"),

        pl.col("tipo_de_emenda").alias("tipo_de_emenda"),
        pl.col("convenente").alias("convenente"),
        pl.col("objeto_convenio").alias("objeto_convenio"),
        pl.col("valor_convenio").str.replace_all(r"\.", "").str.replace(",", ".").cast(pl.Float64, strict=False).alias("valor_convenio"),
    
    ])
    .unique(subset=['numero_convenio', 'codigo_da_emenda'])
    ).sort(by='data_publicacao_convenio', descending=True)


fato_convenios.write_csv(r"C:\Users\Gabriel Barbosa\Downloads\fato_convenios.csv", include_header=True, separator=',', )
print(fato_convenios)

shape: (22_956, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ codigo_da ┆ codigo_fu ┆ codigo_su ┆ numero_co ┆ … ┆ tipo_de_e ┆ convenent ┆ objeto_co ┆ valor_co │
│ _emenda   ┆ ncao      ┆ bfuncao   ┆ nvenio    ┆   ┆ menda     ┆ e         ┆ nvenio    ┆ nvenio   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆ i64       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 202640820 ┆ 8         ┆ 244       ┆ 7AACXM    ┆ … ┆ Emenda    ┆ ASSOCIACA ┆ Promover  ┆ 150000,0 │
│ 006       ┆           ┆           ┆           ┆   ┆ Individua ┆ O CIVIL   ┆ a capacit ┆ 0        │
│           ┆           ┆           ┆           ┆   ┆ l - Trans ┆ ALTERNATI ┆ acao de   ┆          │
│           ┆           ┆           ┆           ┆   ┆ ferên…    ┆ VA T…     ┆ pess…     ┆          │
│ 202640820 ┆ 8         ┆ 244       ┆ 7AACXN    ┆ … ┆ Emenda    ┆ ASSOCIACA ┆ null      ┆ 150000,0 │
│ 006       ┆           ┆           ┆           ┆   ┆ Individua ┆ O DE      ┆           ┆ 0        │
│           ┆           ┆           ┆           ┆   ┆ l - Trans ┆ MORADORES ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ferên…    ┆ DA SAM…   ┆           ┆          │
│ 202644050 ┆ 15        ┆ 845       ┆ 998817    ┆ … ┆ Emenda    ┆ INSTITUTO ┆ Apoio a   ┆ 2500000, │
│ 006       ┆           ┆           ┆           ┆   ┆ Individua ┆ GLOBAL    ┆ execucao  ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆ l - Trans ┆ ATTITUDE  ┆ do        ┆          │
│           ┆           ┆           ┆           ┆   ┆ ferên…    ┆           ┆ Projeto   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Se…       ┆          │
│ 202644830 ┆ 15        ┆ 845       ┆ 998816    ┆ … ┆ Emenda    ┆ INSTITUTO ┆ Consolida ┆ 800000,0 │
│ 017       ┆           ┆           ┆           ┆   ┆ Individua ┆ RAIZES EM ┆ r o Obser ┆ 0        │
│           ┆           ┆           ┆           ┆   ┆ l - Trans ┆ MOVIMENTO ┆ vatorio   ┆          │
│           ┆           ┆           ┆           ┆   ┆ ferên…    ┆           ┆ de P…     ┆          │
│ 202644050 ┆ 15        ┆ 845       ┆ 998811    ┆ … ┆ Emenda    ┆ INSTITUTO ┆ O         ┆ 500000,0 │
│ 006       ┆           ┆           ┆           ┆   ┆ Individua ┆ DE DEFESA ┆ presente  ┆ 0        │
│           ┆           ┆           ┆           ┆   ┆ l - Trans ┆ DOS       ┆ Termo de  ┆          │
│           ┆           ┆           ┆           ┆   ┆ ferên…    ┆ DIREIT…   ┆ Fomento   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ de…       ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 201524570 ┆ 6         ┆ 182       ┆ 702018    ┆ … ┆ Emenda    ┆ MUNICIPIO ┆ Obras de  ┆ 13655769 │
│ 006       ┆           ┆           ┆           ┆   ┆ Individua ┆ DE        ┆ Protecao  ┆ ,26      │
│           ┆           ┆           ┆           ┆   ┆ l - Trans ┆ PAULISTA  ┆ das       ┆          │
│           ┆           ┆           ┆           ┆   ┆ ferên…    ┆           ┆ Estrutur… ┆          │
│ 201532990 ┆ 10        ┆ 302       ┆ 821948    ┆ … ┆ Emenda    ┆ INSTITUTO ┆ AQUISICAO ┆ 200000,0 │
│ 007       ┆           ┆           ┆           ┆   ┆ Individua ┆ DE        ┆ DE EQUIPA ┆ 0        │
│           ┆           ┆           ┆           ┆   ┆ l - Trans ┆ MEDICINA  ┆ MENTO E   ┆          │
│           ┆           ┆           ┆           ┆   ┆ ferên…    ┆ INTEGRAL… ┆ MAT…      ┆          │
│ 202081001 ┆ 12        ┆ 368       ┆ 599981    ┆ … ┆ Emenda de ┆ MUNICIPIO ┆ ESTE      ┆ 1200000, │
│ 503       ┆           ┆           ┆           ┆   ┆ Relator   ┆ DE        ┆ CONVENIO  ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆           ┆ CURRAIS   ┆ TEM POR   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ NOVOS     ┆ OBJETO C… ┆          │
│ 201522110 ┆ 5         ┆ 571       ┆ 480096    ┆ … ┆ Emenda    ┆ FUNDACAO  ┆ ATENDER A ┆ 18512554 │
│ 023       ┆           ┆           ┆           ┆   ┆ Individua ┆ DE APOIO  ┆ MANUTENCA ┆ ,71      │
│           ┆           ┆           ┆           ┆   ┆ l - Trans ┆ A UNIVERS ┆ O OPERATI ┆          │
│           ┆           ┆           ┆           ┆   ┆ ferên…    ┆ IDA…      ┆ VA…       ┆          │
│ 201524780 ┆ 5         ┆ 571       ┆ 480096    ┆ … ┆ Emenda    ┆ FUNDACAO  ┆ ATENDER A ┆ 18512554 │
│ 015       ┆           ┆           ┆           ┆   ┆ Individua ┆ DE APOIO  ┆ MANUTENCA ┆ ,71      │
│           ┆           ┆           ┆           ┆   ┆ l - Trans ┆ A UNIVERS ┆ O OPERATI ┆          │
│           ┆           ┆           ┆           ┆   ┆ ferên…    ┆ IDA…      ┆ VA…       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘